# Disable the "core" elasticsearch plugins
disablePlugins:
  - lando-elasticsearch

# Make sure we are dogfooding this plugin for testing purposes
plugins:
  "@lando/elasticsearch": /home/runner/work/elasticsearch/elasticsearch

# Disable metrics reporting
stats:
  - report: false
    url: https://metrics.lando.dev


