http:
  port: 9200
path:
  data: /bitnami/elasticsearch/data
transport:
  tcp:
    port: 9300
network:
  host: 172.23.0.2
  publish_host: 172.23.0.2
  bind_host: 0.0.0.0
cluster:
  name: bespin
node:
  name: lando
  master: true
  data: true
  ingest: true
discovery:
  type: single-node
plugin:
  mandatory: analysis-icu
