name: lando-elasticsearch-8
services:
  defaults:
    type: elasticsearch:8
  patch:
    type: elasticsearch:8.17.4

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/elasticsearch": ./../../
