name: lando-elasticsearch-5
services:
  defaults:
    type: elasticsearch:5
    portforward: true
  patch:
    type: elasticsearch:5.6.15
    portforward: true

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/elasticsearch": ./../../

