name: lando-elasticsearch-7
services:
  defaults:
    type: elasticsearch:7
  patch:
    type: elasticsearch:7.17.5

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/elasticsearch": ../..
