name: lando-elasticsearch
services:
  custom:
    type: elasticsearch:7
    portforward: 4547
    mem: 1026m
    plugins:
      - analysis-icu
    config:
      server: config/custom.yml

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/elasticsearch": ../..
