name: lando-elasticsearch-9
services:
  defaults:
    type: elasticsearch:9
  patch:
    type: elasticsearch:9.0.3

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/elasticsearch": ../..
